In [1]:
import numpy as np
from scipy.optimize import minimize
from sympy import symbols, sqrt, solve

In [2]:
def pairwise_sum(M):
    """
    Compute the sum \sum_{i \neq j} \frac{1}{||m[i] - m[j]||}.

    Parameters:
        M (numpy.ndarray): A matrix of shape (n, d), where n is the number of vectors and d is their dimensionality.

    Returns:
        float: The computed sum.
    """
    n = M.shape[0]
    total_sum = 0.0

    for i in range(n):
        for j in range(n):
            if i != j:
                diff = M[i] - M[j]
                norm = np.linalg.norm(diff)
                if norm > 0:  # Avoid division by zero
                    total_sum += 1 / norm

    return total_sum

def pairwise_distances(M):
    """
    Compute the pairwise distance matrix for the rows of matrix M.

    Parameters:
        M (numpy.ndarray): A matrix of shape (n, d), where n is the number of vectors and d is their dimensionality.

    Returns:
        numpy.ndarray: A matrix D of shape (n, n), where D[i, j] = ||m[i] - m[j]||.
    """
    n = M.shape[0]
    D = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            if i != j:
                D[i, j] = np.linalg.norm(M[i] - M[j])

    return D

# Example usage:
M = np.array([[1, 2], [3, 4], [5, 6]])  # Example 2D matrix
result = pairwise_sum(M)
print("Sum:", result)

distance_matrix = pairwise_distances(M)
print("Pairwise distances:\n", distance_matrix)


Sum: 1.7677669529663687
Pairwise distances:
 [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_537/3743854625.py:2: SyntaxWarning: invalid escape sequence '\s'
  """


In [3]:
M = np.array([
    [1, 0, 0],
    [-0.50000725,  0.61236069, -0.6123784],
    [-0.50000722, -0.61237838,  0.61236072]
])
print(pairwise_sum(M))
print(pairwise_distances(M))

3.464101429890209
[[0.         1.73205504 1.73205502]
 [1.73205504 0.         1.73204264]
 [1.73205502 1.73204264 0.        ]]


In [13]:
# Define the objective function
def f(vars):
    y1, y2, y3, z1, z2, z3 = vars
    term1 = 1 / np.sqrt((1 - y1)**2 + y2**2 + y3**2)
    term2 = 1 / np.sqrt((1 - z1)**2 + z2**2 + z3**2)
    term3 = 1 / np.sqrt((y1 - z1)**2 + (y2 - z2)**2 + (y3 - z3)**2)
    return (term1 + term2 + term3)  # Negative for maximization

# Define the constraints
constraints = [
    {'type': 'eq', 'fun': lambda vars: vars[0]**2 + vars[1]**2 + vars[2]**2 - 1},  # y1^2 + y2^2 + y3^2 = 1
    {'type': 'eq', 'fun': lambda vars: vars[3]**2 + vars[4]**2 + vars[5]**2 - 1}   # z1^2 + z2^2 + z3^2 = 1
]

# Initial guess
initial_guess = [0, 1, 0, 0, 0, 1]

# Solve using SciPy minimize
result = minimize(f, initial_guess, constraints=constraints)
print("Optimal solution:", result.x)
print("Minimum value:", result.fun)

Optimal solution: [-0.50000725  0.61236069 -0.6123784  -0.50000722 -0.61237838  0.61236072]
Minimum value: 1.7320507175316286


In [ ]:
from sage.all import *

# Define variables
y1, y2, y3, z1, z2, z3 = var('y1 y2 y3 z1 z2 z3')
lambda1, lambda2 = var('lambda1 lambda2')

# Define the function and constraints
f = 1 / sqrt((1 - y1)^2 + y2^2 + y3^2) + \
    1 / sqrt((1 - z1)^2 + z2^2 + z3^2) + \
    1 / sqrt((y1 - z1)^2 + (y2 - z2)^2 + (y3 - z3)^2)

constraint1 = y1^2 + y2^2 + y3^2 - 1
constraint2 = z1^2 + z2^2 + z3^2 - 1

# Set up Lagrange equations
lagrange_eqs = [
    diff(f, y1) + 2 * lambda1 * y1 == 0,
    diff(f, y2) + 2 * lambda1 * y2 == 0,
    diff(f, y3) + 2 * lambda1 * y3 == 0,
    diff(f, z1) + 2 * lambda2 * z1 == 0,
    diff(f, z2) + 2 * lambda2 * z2 == 0,
    diff(f, z3) + 2 * lambda2 * z3 == 0,
    constraint1 == 0,
    constraint2 == 0
]

# Solve the system
solutions = solve(lagrange_eqs, [y1, y2, y3, z1, z2, z3, lambda1, lambda2])
print(solutions)